### ISSUE TITLE
New ES features can make this shiny and new again

### ISSUE THREAD

**Issue by wesleytodd** [Pita/channels#6]
Hi @Pita,

I was wondering if you would be willing to let me take this and re-write it with shiny new ES features?  Here is an example on top of async iterators:

https://gist.github.com/wesleytodd/ad293325a80de4be6cc4dd804441a99f

There is also this proposal which I might consider if it moves forward: 

https://github.com/tc39/proposal-emitter

If you are comfortable handing the library and npm publish rights over to me I would like to make this happen.  Much better revive this package name than publish my implementation under a different name.

Also, any feedback welcome on the direction.

**Comment by Pita** [comment]
Hello @wesleytodd,

This is super old code and I'm happy to hear that there is a better way to do this now. I'm not protective of the npm name. It's just that this package is used by another package called ueberdb, which in turn is used by etherpad lite. These are projects I used to be involved in and they are still very popular. I'm fearing that by passing the npm package name these projects might be open to code injection. 

I wonder if there is a way of passing on the name without endagering these projects. I'm open to suggestions. I don't know the details of npm permissions and so on

cc: @JohnMcLear 

Pita

**Comment by JohnMcLear** [comment]
He's only talking about "upgrading" to new ES features, he's not talking about changing the API or namespace.



You can add him as a maintainer/collaborator/owner on both github and npm with no changes upstream, we do it all the time, it's really easy (one liner).







-----Original message-----

**Comment by wesleytodd** [comment]
Well I think I would probably change the api.  The point would be to get the same feature set on top of promises and async iterators.  So the `emit` would return a promise which would resolve when all the subscribers finished processing.  You can see in the gist I posted the api I was thinking.

It is in spirit the same, but because the world has changed so much from when this was written, there is just a better more robust way to get the same general functionality.  The reason I think this is the right package name is because it is technically coroutines and go-style channels which I have implemented.

**Comment by wesleytodd** [comment]
https://www.npmjs.com/package/ueberdb

Looks like this is deprecated and also unused.  It looks like actually `channels` is [depended on directly by Etherpad Lite](https://github.com/ether/etherpad-lite/blob/develop/src/package.json#L35).

If you all agree I can work with @JohnMcLear to make sure that the `v1` would still satisfy their needs.  That said, I would not be making any changes to he `0.x` line, so if there were updates we could just support both versions until Etherpad Lite could update.

**Comment by JohnMcLear** [comment]
See how https://github.com/request/request handles this for good practice.

-----Original message-----

**Comment by JohnMcLear** [comment]
mux8tor is the maintainer for Etherpad now and has been for some time, FYI @pita.



afaik Etherpad uses npm package ueberdb2.







-----Original message-----

**Comment by wesleytodd** [comment]
@JohnMcLear not sure what you mean.  Handles multiple release lines, or major version changes?  I am well aware of how to do it (I help maintain Express, and a few other popular libs and an active member of the Node.js Core Package Maintenance WG), so have no fear that I will mess it up and break you 😄 .  But if you have questions or concerns about how I would plan to do the upgrade I would love to hear them!

**Comment by Pita** [comment]
For me its ok, just leave the current versions published untouched please. Then start with a version number 0.1 or bigger. 

Bot ueberdb and etherpad lite are fixed to 0.0.4

**Comment by Pita** [comment]
What is your npm name?

**Comment by wesleytodd** [comment]
`wesleytodd`.  I for sure wouldn't publish anything under `1.0.0`.   If in the future, if either of those projects need updates we can work on getting those done for them.  But it would seem like ~5~7 years of usage untouched means it will be unlikely :)

**Comment by Pita** [comment]
@wesleytodd I gave you access :)
